### ISSUE TITLE
Will there be a chrome version?

### ISSUE THREAD

**Issue by anotherduckling** [Cyan903/Animepahe-plus#3]

**Comment by Cyan903** [comment]
I never planned on it. I've never made a chrome extension and haven't used chrome in years. But I took a look at the chrome extension documentation and it didn't seem too difficult to port.

https://github.com/Cyan903/Animepahe-plus/tree/chrome-rework

Did some testing and from what I can see, all the features seem to be working properly. I'll probably need to check more things beforehand, and I doubt I'll be able to get this on the webstore. I'll try my best to get a fully functional chrome version going.

**Comment by anotherduckling** [comment]
thanks a lot
